// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PicklinkBackend.Data;

#nullable disable

namespace PicklinkBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260611102102_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PicklinkBackend.Models.Amenity", b =>
                {
                    b.Property<int>("AmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("amenityId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityId"));

                    b.Property<string>("AmenityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("amenityName");

                    b.Property<bool>("IsFree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isFree");

                    b.Property<int>("VenueId")
                        .HasColumnType("int")
                        .HasColumnName("venueId");

                    b.HasKey("AmenityId");

                    b.HasIndex("VenueId");

                    b.ToTable("AMENITY", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bookingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int>("CourtId")
                        .HasColumnType("int")
                        .HasColumnName("courtId");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("endTime");

                    b.Property<int?>("MatchId")
                        .HasColumnType("int")
                        .HasColumnName("matchId");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("playerId");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("startTime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.HasKey("BookingId");

                    b.HasIndex(new[] { "CourtId" }, "IX_BOOKING_courtId");

                    b.HasIndex(new[] { "MatchId" }, "IX_BOOKING_matchId");

                    b.HasIndex(new[] { "PlayerId" }, "IX_BOOKING_playerId");

                    b.HasIndex(new[] { "StartTime" }, "IX_BOOKING_startTime");

                    b.ToTable("BOOKING", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.BookingRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ruleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleId"));

                    b.Property<string>("RuleContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ruleContent");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ruleType");

                    b.Property<int>("VenueId")
                        .HasColumnType("int")
                        .HasColumnName("venueId");

                    b.HasKey("RuleId");

                    b.HasIndex("VenueId");

                    b.ToTable("BOOKING_RULES", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.Conversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("conversationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversationId"));

                    b.Property<string>("ConversationName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("conversationName");

                    b.Property<string>("ConversationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Direct")
                        .HasColumnName("conversationType");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("datetime")
                        .HasColumnName("lastMessageAt");

                    b.HasKey("ConversationId");

                    b.HasIndex(new[] { "LastMessageAt" }, "IX_CONVERSATION_lastMessageAt")
                        .IsDescending();

                    b.ToTable("CONVERSATION", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.ConversationParticipant", b =>
                {
                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("conversationId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("joinedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("datetime")
                        .HasColumnName("lastReadAt");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex(new[] { "UserId" }, "IX_CONV_PARTICIPANT_userId");

                    b.ToTable("CONVERSATION_PARTICIPANT", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.Court", b =>
                {
                    b.Property<int>("CourtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("courtId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourtId"));

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Available")
                        .HasColumnName("availabilityStatus");

                    b.Property<int>("CourtNumber")
                        .HasColumnType("int")
                        .HasColumnName("courtNumber");

                    b.Property<bool>("IsIndoor")
                        .HasColumnType("bit")
                        .HasColumnName("isIndoor");

                    b.Property<string>("SurfaceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("surfaceType");

                    b.Property<int>("VenueId")
                        .HasColumnType("int")
                        .HasColumnName("venueId");

                    b.HasKey("CourtId");

                    b.HasIndex(new[] { "VenueId" }, "IX_COURT_venueId");

                    b.ToTable("COURT", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.Friendship", b =>
                {
                    b.Property<int>("FriendshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("friendshipId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FriendshipId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("receiverId");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int")
                        .HasColumnName("requesterId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("FriendshipId");

                    b.HasIndex(new[] { "ReceiverId", "Status" }, "IX_FRIENDSHIP_receiver");

                    b.HasIndex(new[] { "RequesterId", "Status" }, "IX_FRIENDSHIP_requester");

                    b.HasIndex(new[] { "RequesterId", "ReceiverId" }, "UQ_FRIENDSHIP_PAIR")
                        .IsUnique();

                    b.ToTable("FRIENDSHIP", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.GroupMember", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("groupId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("joinedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Member")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Accepted")
                        .HasColumnName("status");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex(new[] { "UserId", "Status" }, "IX_GROUP_MEMBER_userId");

                    b.ToTable("GROUP_MEMBER", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.InventoryItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("itemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("itemName");

                    b.Property<double>("PricePerUnit")
                        .HasColumnType("float")
                        .HasColumnName("pricePerUnit");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int")
                        .HasColumnName("providerId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Available")
                        .HasColumnName("status");

                    b.HasKey("ItemId");

                    b.HasIndex("ProviderId");

                    b.ToTable("INVENTORY_ITEM", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.MarketplaceProvider", b =>
                {
                    b.Property<int>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("providerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProviderId"));

                    b.Property<string>("ProviderType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("providerType");

                    b.Property<string>("Specialty")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("specialty");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("ProviderId");

                    b.HasIndex(new[] { "UserId" }, "IX_MARKETPLACE_PROVIDER_userId");

                    b.ToTable("MARKETPLACE_PROVIDER", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("matchId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchId"));

                    b.Property<int>("MatchSkillLevel")
                        .HasColumnType("int")
                        .HasColumnName("matchSkillLevel");

                    b.Property<DateTime>("MatchTime")
                        .HasColumnType("datetime")
                        .HasColumnName("matchTime");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("matchType");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Scheduled")
                        .HasColumnName("status");

                    b.Property<int?>("Team1Id")
                        .HasColumnType("int")
                        .HasColumnName("team1Id");

                    b.Property<int?>("Team2Id")
                        .HasColumnType("int")
                        .HasColumnName("team2Id");

                    b.Property<int?>("WinningTeamId")
                        .HasColumnType("int")
                        .HasColumnName("winningTeamId");

                    b.HasKey("MatchId");

                    b.HasIndex("Team1Id");

                    b.HasIndex("Team2Id");

                    b.HasIndex("WinningTeamId");

                    b.HasIndex(new[] { "MatchTime" }, "IX_MATCH_matchTime");

                    b.HasIndex(new[] { "Status" }, "IX_MATCH_status");

                    b.ToTable("MATCH", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.MatchCheckIn", b =>
                {
                    b.Property<int>("CheckInId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("checkinId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckInId"));

                    b.Property<DateTime>("CheckedInAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("checkedInAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MatchId")
                        .HasColumnType("int")
                        .HasColumnName("matchId");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("playerId");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("staffId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Present")
                        .HasColumnName("status");

                    b.HasKey("CheckInId");

                    b.HasIndex("StaffId");

                    b.HasIndex(new[] { "MatchId" }, "IX_MATCH_CHECKIN_matchId");

                    b.HasIndex(new[] { "PlayerId" }, "IX_MATCH_CHECKIN_playerId");

                    b.HasIndex(new[] { "MatchId", "PlayerId" }, "UQ_MATCH_CHECKIN_UNIQUE")
                        .IsUnique();

                    b.ToTable("MATCH_CHECKIN", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.MatchParticipant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("participantId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"));

                    b.Property<string>("Class")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("class");

                    b.Property<int>("MatchId")
                        .HasColumnType("int")
                        .HasColumnName("matchId");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("playerId");

                    b.HasKey("ParticipantId");

                    b.HasIndex(new[] { "MatchId" }, "IX_MATCH_PARTICIPANT_match");

                    b.HasIndex(new[] { "PlayerId" }, "IX_MATCH_PARTICIPANT_player");

                    b.ToTable("MATCH_PARTICIPANT", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("messageId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("conversationId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mediaUrl");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Text")
                        .HasColumnName("messageType");

                    b.Property<int?>("ReplyToMessageId")
                        .HasColumnType("int")
                        .HasColumnName("replyToMessageId");

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("senderId");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("sentAt")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MessageId");

                    b.HasIndex("ReplyToMessageId");

                    b.HasIndex(new[] { "ConversationId", "SentAt" }, "IX_MESSAGE_conversationId")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "SenderId" }, "IX_MESSAGE_senderId");

                    b.ToTable("MESSAGE", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.NotificationLog", b =>
                {
                    b.Property<int>("NotifId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notifId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotifId"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("isRead");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("NotifId");

                    b.HasIndex(new[] { "UserId" }, "IX_NOTIF_userId");

                    b.ToTable("NOTIFICATION_LOG", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("paymentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<double>("Amount")
                        .HasColumnType("float")
                        .HasColumnName("amount");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("bookingId");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime")
                        .HasColumnName("paidAt");

                    b.Property<int>("PayerId")
                        .HasColumnType("int")
                        .HasColumnName("payerId");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("paymentMethod");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.HasKey("PaymentId");

                    b.HasIndex(new[] { "BookingId" }, "IX_PAYMENT_bookingId");

                    b.HasIndex(new[] { "PayerId" }, "IX_PAYMENT_payerId");

                    b.ToTable("PAYMENT", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("playerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("PlayerSubType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("playerSubType");

                    b.Property<int>("Prestige")
                        .HasColumnType("int")
                        .HasColumnName("prestige");

                    b.Property<double>("SkillLevel")
                        .HasColumnType("float")
                        .HasColumnName("skillLevel");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("PlayerId");

                    b.HasIndex(new[] { "UserId" }, "IX_PLAYER_userId");

                    b.ToTable("PLAYER", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.PlayerTeamRoster", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("playerId");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("teamId");

                    b.Property<DateOnly>("JoinedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("joinedDate")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.HasKey("PlayerId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("PLAYER_TEAM_ROSTER", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("postId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("authorId");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expiresAt");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Post")
                        .HasColumnName("postType");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Public")
                        .HasColumnName("visibility");

                    b.HasKey("PostId");

                    b.HasIndex(new[] { "AuthorId" }, "IX_POST_authorId");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_POST_createdAt")
                        .IsDescending();

                    b.HasIndex(new[] { "ExpiresAt" }, "IX_POST_expiresAt")
                        .HasFilter("([expiresAt] IS NOT NULL)");

                    b.ToTable("POST", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.PostComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("commentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int")
                        .HasColumnName("parentCommentId");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("postId");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("CommentId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ParentCommentId" }, "IX_POST_COMMENT_parent")
                        .HasFilter("([parentCommentId] IS NOT NULL)");

                    b.HasIndex(new[] { "PostId", "CreatedAt" }, "IX_POST_COMMENT_postId");

                    b.ToTable("POST_COMMENT", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.PostLike", b =>
                {
                    b.Property<int>("LikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("likeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LikeId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("postId");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Like")
                        .HasColumnName("reactionType");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("LikeId");

                    b.HasIndex(new[] { "PostId" }, "IX_POST_LIKE_postId");

                    b.HasIndex(new[] { "UserId" }, "IX_POST_LIKE_userId");

                    b.HasIndex(new[] { "PostId", "UserId" }, "UQ_POST_LIKE_USER_POST")
                        .IsUnique();

                    b.ToTable("POST_LIKE", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.PostMedia", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mediaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("displayOrder");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Image")
                        .HasColumnName("mediaType");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mediaUrl");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("postId");

                    b.HasKey("MediaId");

                    b.HasIndex(new[] { "PostId", "DisplayOrder" }, "IX_POST_MEDIA_postId");

                    b.ToTable("POST_MEDIA", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.RatingHistory", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ratingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<int>("TargetId")
                        .HasColumnType("int")
                        .HasColumnName("targetId");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("targetType");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("RatingId");

                    b.HasIndex(new[] { "TargetId", "TargetType" }, "IX_RATING_HISTORY_target");

                    b.HasIndex(new[] { "UserId" }, "IX_RATING_HISTORY_userId");

                    b.ToTable("RATING_HISTORY", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.Scorecard", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("gameId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<int>("CourtId")
                        .HasColumnType("int")
                        .HasColumnName("courtId");

                    b.Property<int>("MatchId")
                        .HasColumnType("int")
                        .HasColumnName("matchId");

                    b.Property<string>("ScoreInfo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scoreInfo");

                    b.HasKey("GameId");

                    b.HasIndex("CourtId");

                    b.HasIndex("MatchId");

                    b.ToTable("SCORECARD", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.SkillMatchup", b =>
                {
                    b.Property<int>("MatchupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("matchupId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchupId"));

                    b.Property<int>("MatchId")
                        .HasColumnType("int")
                        .HasColumnName("matchId");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("playerId");

                    b.Property<int>("SkillDelta")
                        .HasColumnType("int")
                        .HasColumnName("skillDelta");

                    b.HasKey("MatchupId");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("SKILL_MATCHUP", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.SocialGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("groupId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("coverImageUrl");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("groupName");

                    b.Property<string>("GroupType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Public")
                        .HasColumnName("groupType");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("ownerId");

                    b.HasKey("GroupId");

                    b.HasIndex(new[] { "OwnerId" }, "IX_SOCIAL_GROUP_ownerId");

                    b.ToTable("SOCIAL_GROUP", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("staffId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.Property<int>("VenueId")
                        .HasColumnType("int")
                        .HasColumnName("venueId");

                    b.HasKey("StaffId");

                    b.HasIndex(new[] { "UserId" }, "IX_STAFF_userId");

                    b.HasIndex(new[] { "VenueId" }, "IX_STAFF_venueId");

                    b.ToTable("STAFF", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("teamId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<int>("CaptainId")
                        .HasColumnType("int")
                        .HasColumnName("captainId");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("teamName");

                    b.HasKey("TeamId");

                    b.HasIndex("CaptainId");

                    b.ToTable("TEAM", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tournamentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TournamentId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("endDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("startDate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Upcoming")
                        .HasColumnName("status");

                    b.HasKey("TournamentId");

                    b.ToTable("TOURNAMENT", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("passwordHash");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("profileImageUrl");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("userType");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "UQ_USER_email")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ_USER_username")
                        .IsUnique();

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("venueId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time")
                        .HasColumnName("closeTime");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time")
                        .HasColumnName("openTime");

                    b.Property<double>("OverallRating")
                        .HasColumnType("float")
                        .HasColumnName("overallRating");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("ownerId");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phoneNumber");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("venueName");

                    b.HasKey("VenueId");

                    b.HasIndex(new[] { "OwnerId" }, "IX_VENUE_ownerId");

                    b.ToTable("VENUE", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.VenueAuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("logId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("action");

                    b.Property<int>("ActorId")
                        .HasColumnType("int")
                        .HasColumnName("actorId");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("VenueId")
                        .HasColumnType("int")
                        .HasColumnName("venueId");

                    b.HasKey("LogId");

                    b.HasIndex("ActorId");

                    b.HasIndex(new[] { "VenueId" }, "IX_VENUE_AUDIT_venueId");

                    b.ToTable("VENUE_AUDIT_LOG", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.VenueOwner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ownerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnerId"));

                    b.Property<string>("SpecialPermissions")
                        .HasColumnType("text")
                        .HasColumnName("specialPermissions");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("OwnerId");

                    b.HasIndex(new[] { "UserId" }, "IX_VENUE_OWNER_userId");

                    b.ToTable("VENUE_OWNER", (string)null);
                });

            modelBuilder.Entity("TournamentTeam", b =>
                {
                    b.Property<int>("TournamentId")
                        .HasColumnType("int")
                        .HasColumnName("tournamentId");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("teamId");

                    b.HasKey("TournamentId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("TOURNAMENT_TEAM", (string)null);
                });

            modelBuilder.Entity("PicklinkBackend.Models.Amenity", b =>
                {
                    b.HasOne("PicklinkBackend.Models.Venue", "Venue")
                        .WithMany("Amenities")
                        .HasForeignKey("VenueId")
                        .IsRequired()
                        .HasConstraintName("FK_AMENITY_VENUE");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Booking", b =>
                {
                    b.HasOne("PicklinkBackend.Models.Court", "Court")
                        .WithMany("Bookings")
                        .HasForeignKey("CourtId")
                        .IsRequired()
                        .HasConstraintName("FK_BOOKING_COURT");

                    b.HasOne("PicklinkBackend.Models.Match", "Match")
                        .WithMany("Bookings")
                        .HasForeignKey("MatchId")
                        .HasConstraintName("FK_BOOKING_MATCH");

                    b.HasOne("PicklinkBackend.Models.Player", "Player")
                        .WithMany("Bookings")
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("FK_BOOKING_PLAYER");

                    b.Navigation("Court");

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PicklinkBackend.Models.BookingRule", b =>
                {
                    b.HasOne("PicklinkBackend.Models.Venue", "Venue")
                        .WithMany("BookingRules")
                        .HasForeignKey("VenueId")
                        .IsRequired()
                        .HasConstraintName("FK_BOOKING_RULES_VENUE");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("PicklinkBackend.Models.ConversationParticipant", b =>
                {
                    b.HasOne("PicklinkBackend.Models.Conversation", "Conversation")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("ConversationId")
                        .IsRequired()
                        .HasConstraintName("FK_CONV_PARTICIPANT_CONVERSATION");

                    b.HasOne("PicklinkBackend.Models.User", "User")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_CONV_PARTICIPANT_USER");

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Court", b =>
                {
                    b.HasOne("PicklinkBackend.Models.Venue", "Venue")
                        .WithMany("Courts")
                        .HasForeignKey("VenueId")
                        .IsRequired()
                        .HasConstraintName("FK_COURT_VENUE");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Friendship", b =>
                {
                    b.HasOne("PicklinkBackend.Models.User", "Receiver")
                        .WithMany("FriendshipReceivers")
                        .HasForeignKey("ReceiverId")
                        .IsRequired()
                        .HasConstraintName("FK_FRIENDSHIP_RECEIVER");

                    b.HasOne("PicklinkBackend.Models.User", "Requester")
                        .WithMany("FriendshipRequesters")
                        .HasForeignKey("RequesterId")
                        .IsRequired()
                        .HasConstraintName("FK_FRIENDSHIP_REQUESTER");

                    b.Navigation("Receiver");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("PicklinkBackend.Models.GroupMember", b =>
                {
                    b.HasOne("PicklinkBackend.Models.SocialGroup", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_GROUP_MEMBER_GROUP");

                    b.HasOne("PicklinkBackend.Models.User", "User")
                        .WithMany("GroupMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_GROUP_MEMBER_USER");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklinkBackend.Models.InventoryItem", b =>
                {
                    b.HasOne("PicklinkBackend.Models.MarketplaceProvider", "Provider")
                        .WithMany("InventoryItems")
                        .HasForeignKey("ProviderId")
                        .IsRequired()
                        .HasConstraintName("FK_INVENTORY_ITEM_PROVIDER");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("PicklinkBackend.Models.MarketplaceProvider", b =>
                {
                    b.HasOne("PicklinkBackend.Models.User", "User")
                        .WithMany("MarketplaceProviders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_MARKETPLACE_PROVIDER_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Match", b =>
                {
                    b.HasOne("PicklinkBackend.Models.Team", "Team1")
                        .WithMany("MatchTeam1s")
                        .HasForeignKey("Team1Id")
                        .HasConstraintName("FK_MATCH_TEAM1");

                    b.HasOne("PicklinkBackend.Models.Team", "Team2")
                        .WithMany("MatchTeam2s")
                        .HasForeignKey("Team2Id")
                        .HasConstraintName("FK_MATCH_TEAM2");

                    b.HasOne("PicklinkBackend.Models.Team", "WinningTeam")
                        .WithMany("MatchWinningTeams")
                        .HasForeignKey("WinningTeamId")
                        .HasConstraintName("FK_MATCH_WINNER");

                    b.Navigation("Team1");

                    b.Navigation("Team2");

                    b.Navigation("WinningTeam");
                });

            modelBuilder.Entity("PicklinkBackend.Models.MatchCheckIn", b =>
                {
                    b.HasOne("PicklinkBackend.Models.Match", "Match")
                        .WithMany("MatchCheckIns")
                        .HasForeignKey("MatchId")
                        .IsRequired()
                        .HasConstraintName("FK_MATCH_CHECKIN_MATCH");

                    b.HasOne("PicklinkBackend.Models.Player", "Player")
                        .WithMany("MatchCheckIns")
                        .HasForeignKey("PlayerId")
                        .IsRequired()
                        .HasConstraintName("FK_MATCH_CHECKIN_PLAYER");

                    b.HasOne("PicklinkBackend.Models.Staff", "Staff")
                        .WithMany("MatchCheckIns")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK_MATCH_CHECKIN_STAFF");

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PicklinkBackend.Models.MatchParticipant", b =>
                {
                    b.HasOne("PicklinkBackend.Models.Match", "Match")
                        .WithMany("MatchParticipants")
                        .HasForeignKey("MatchId")
                        .IsRequired()
                        .HasConstraintName("FK_MATCH_PARTICIPANT_MATCH");

                    b.HasOne("PicklinkBackend.Models.Player", "Player")
                        .WithMany("MatchParticipants")
                        .HasForeignKey("PlayerId")
                        .IsRequired()
                        .HasConstraintName("FK_MATCH_PARTICIPANT_PLAYER");

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Message", b =>
                {
                    b.HasOne("PicklinkBackend.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .IsRequired()
                        .HasConstraintName("FK_MESSAGE_CONVERSATION");

                    b.HasOne("PicklinkBackend.Models.Message", "ReplyToMessage")
                        .WithMany("InverseReplyToMessage")
                        .HasForeignKey("ReplyToMessageId")
                        .HasConstraintName("FK_MESSAGE_REPLY");

                    b.HasOne("PicklinkBackend.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("FK_MESSAGE_SENDER");

                    b.Navigation("Conversation");

                    b.Navigation("ReplyToMessage");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PicklinkBackend.Models.NotificationLog", b =>
                {
                    b.HasOne("PicklinkBackend.Models.User", "User")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_NOTIFICATION_LOG_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Payment", b =>
                {
                    b.HasOne("PicklinkBackend.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_PAYMENT_BOOKING");

                    b.HasOne("PicklinkBackend.Models.Player", "Payer")
                        .WithMany("Payments")
                        .HasForeignKey("PayerId")
                        .IsRequired()
                        .HasConstraintName("FK_PAYMENT_PAYER");

                    b.Navigation("Booking");

                    b.Navigation("Payer");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Player", b =>
                {
                    b.HasOne("PicklinkBackend.Models.User", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_PLAYER_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklinkBackend.Models.PlayerTeamRoster", b =>
                {
                    b.HasOne("PicklinkBackend.Models.Player", "Player")
                        .WithMany("PlayerTeamRosters")
                        .HasForeignKey("PlayerId")
                        .IsRequired()
                        .HasConstraintName("FK_PTR_PLAYER");

                    b.HasOne("PicklinkBackend.Models.Team", "Team")
                        .WithMany("PlayerTeamRosters")
                        .HasForeignKey("TeamId")
                        .IsRequired()
                        .HasConstraintName("FK_PTR_TEAM");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Post", b =>
                {
                    b.HasOne("PicklinkBackend.Models.User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK_POST_AUTHOR");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("PicklinkBackend.Models.PostComment", b =>
                {
                    b.HasOne("PicklinkBackend.Models.PostComment", "ParentComment")
                        .WithMany("InverseParentComment")
                        .HasForeignKey("ParentCommentId")
                        .HasConstraintName("FK_POST_COMMENT_PARENT");

                    b.HasOne("PicklinkBackend.Models.Post", "Post")
                        .WithMany("PostComments")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_POST_COMMENT_POST");

                    b.HasOne("PicklinkBackend.Models.User", "User")
                        .WithMany("PostComments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_POST_COMMENT_USER");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklinkBackend.Models.PostLike", b =>
                {
                    b.HasOne("PicklinkBackend.Models.Post", "Post")
                        .WithMany("PostLikes")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_POST_LIKE_POST");

                    b.HasOne("PicklinkBackend.Models.User", "User")
                        .WithMany("PostLikes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_POST_LIKE_USER");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklinkBackend.Models.PostMedia", b =>
                {
                    b.HasOne("PicklinkBackend.Models.Post", "Post")
                        .WithMany("PostMedia")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_POST_MEDIA_POST");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("PicklinkBackend.Models.RatingHistory", b =>
                {
                    b.HasOne("PicklinkBackend.Models.User", "User")
                        .WithMany("RatingHistories")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_RATING_HISTORY_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Scorecard", b =>
                {
                    b.HasOne("PicklinkBackend.Models.Court", "Court")
                        .WithMany("Scorecards")
                        .HasForeignKey("CourtId")
                        .IsRequired()
                        .HasConstraintName("FK_SCORECARD_COURT");

                    b.HasOne("PicklinkBackend.Models.Match", "Match")
                        .WithMany("Scorecards")
                        .HasForeignKey("MatchId")
                        .IsRequired()
                        .HasConstraintName("FK_SCORECARD_MATCH");

                    b.Navigation("Court");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("PicklinkBackend.Models.SkillMatchup", b =>
                {
                    b.HasOne("PicklinkBackend.Models.Match", "Match")
                        .WithMany("SkillMatchups")
                        .HasForeignKey("MatchId")
                        .IsRequired()
                        .HasConstraintName("FK_SKILL_MATCHUP_MATCH");

                    b.HasOne("PicklinkBackend.Models.Player", "Player")
                        .WithMany("SkillMatchups")
                        .HasForeignKey("PlayerId")
                        .IsRequired()
                        .HasConstraintName("FK_SKILL_MATCHUP_PLAYER");

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PicklinkBackend.Models.SocialGroup", b =>
                {
                    b.HasOne("PicklinkBackend.Models.Player", "Owner")
                        .WithMany("SocialGroups")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_SOCIAL_GROUP_OWNER");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Staff", b =>
                {
                    b.HasOne("PicklinkBackend.Models.User", "User")
                        .WithMany("Staff")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_STAFF_USER");

                    b.HasOne("PicklinkBackend.Models.Venue", "Venue")
                        .WithMany("Staff")
                        .HasForeignKey("VenueId")
                        .IsRequired()
                        .HasConstraintName("FK_STAFF_VENUE");

                    b.Navigation("User");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Team", b =>
                {
                    b.HasOne("PicklinkBackend.Models.Player", "Captain")
                        .WithMany("Teams")
                        .HasForeignKey("CaptainId")
                        .IsRequired()
                        .HasConstraintName("FK_TEAM_CAPTAIN");

                    b.Navigation("Captain");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Venue", b =>
                {
                    b.HasOne("PicklinkBackend.Models.VenueOwner", "Owner")
                        .WithMany("Venues")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_VENUE_OWNER");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PicklinkBackend.Models.VenueAuditLog", b =>
                {
                    b.HasOne("PicklinkBackend.Models.User", "Actor")
                        .WithMany("VenueAuditLogs")
                        .HasForeignKey("ActorId")
                        .IsRequired()
                        .HasConstraintName("FK_VENUE_AUDIT_LOG_ACTOR");

                    b.HasOne("PicklinkBackend.Models.Venue", "Venue")
                        .WithMany("VenueAuditLogs")
                        .HasForeignKey("VenueId")
                        .IsRequired()
                        .HasConstraintName("FK_VENUE_AUDIT_LOG_VENUE");

                    b.Navigation("Actor");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("PicklinkBackend.Models.VenueOwner", b =>
                {
                    b.HasOne("PicklinkBackend.Models.User", "User")
                        .WithMany("VenueOwners")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_VENUE_OWNER_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TournamentTeam", b =>
                {
                    b.HasOne("PicklinkBackend.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .IsRequired()
                        .HasConstraintName("FK_TOURNAMENT_TEAM_TEAM");

                    b.HasOne("PicklinkBackend.Models.Tournament", null)
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .IsRequired()
                        .HasConstraintName("FK_TOURNAMENT_TEAM_TOURN");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Booking", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Conversation", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Court", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Scorecards");
                });

            modelBuilder.Entity("PicklinkBackend.Models.MarketplaceProvider", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Match", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("MatchCheckIns");

                    b.Navigation("MatchParticipants");

                    b.Navigation("Scorecards");

                    b.Navigation("SkillMatchups");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Message", b =>
                {
                    b.Navigation("InverseReplyToMessage");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Player", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("MatchCheckIns");

                    b.Navigation("MatchParticipants");

                    b.Navigation("Payments");

                    b.Navigation("PlayerTeamRosters");

                    b.Navigation("SkillMatchups");

                    b.Navigation("SocialGroups");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Post", b =>
                {
                    b.Navigation("PostComments");

                    b.Navigation("PostLikes");

                    b.Navigation("PostMedia");
                });

            modelBuilder.Entity("PicklinkBackend.Models.PostComment", b =>
                {
                    b.Navigation("InverseParentComment");
                });

            modelBuilder.Entity("PicklinkBackend.Models.SocialGroup", b =>
                {
                    b.Navigation("GroupMembers");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Staff", b =>
                {
                    b.Navigation("MatchCheckIns");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Team", b =>
                {
                    b.Navigation("MatchTeam1s");

                    b.Navigation("MatchTeam2s");

                    b.Navigation("MatchWinningTeams");

                    b.Navigation("PlayerTeamRosters");
                });

            modelBuilder.Entity("PicklinkBackend.Models.User", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("FriendshipReceivers");

                    b.Navigation("FriendshipRequesters");

                    b.Navigation("GroupMembers");

                    b.Navigation("MarketplaceProviders");

                    b.Navigation("Messages");

                    b.Navigation("NotificationLogs");

                    b.Navigation("Players");

                    b.Navigation("PostComments");

                    b.Navigation("PostLikes");

                    b.Navigation("Posts");

                    b.Navigation("RatingHistories");

                    b.Navigation("Staff");

                    b.Navigation("VenueAuditLogs");

                    b.Navigation("VenueOwners");
                });

            modelBuilder.Entity("PicklinkBackend.Models.Venue", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("BookingRules");

                    b.Navigation("Courts");

                    b.Navigation("Staff");

                    b.Navigation("VenueAuditLogs");
                });

            modelBuilder.Entity("PicklinkBackend.Models.VenueOwner", b =>
                {
                    b.Navigation("Venues");
                });
#pragma warning restore 612, 618
        }
    }
}
